<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Main" Id="{2eff0738-9ba1-4265-99a1-eaec03d7774a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main
VAR
    KlaarVoorBier : BOOL;
    KlaarVoorSpel : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
KlaarVoorBier := Aangekomen;
KlaarVoorSpel := (Biertjes >= 3);]]></ST>
    </Implementation>
    <LineIds Name="Main">
      <LineId Id="9" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>